
--jdick 215045081 
--EECS3421B Project 2 for Wenxiao Fu
--Oct 30 2020
--Contact Tracing


DROP TABLE Person CASCADE;
DROP TABLE bubble CASCADE;
DROP TABLE Test CASCADE;
DROP TABLE Time_slot CASCADE; --
DROP TABLE Test_type CASCADE;
DROP TABLE Action CASCADE;
DROP TABLE Method CASCADE;
DROP TABLE Place CASCADE;
DROP TABLE Test_centre CASCADE;
DROP TABLE offer CASCADE;
DROP TABLE recon CASCADE;